development:
  adapter: postgresql
  database: assets-tracker_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: assets-tracker_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: assets-tracker_production
  host: localhost
  pool: 5
  timeout: 5000
